***REMOVED***
***REMOVED***
***REMOVED***


***REMOVED***
  final String image;

  const SessionPreview({Key key, this.image***REMOVED***) : super(key: key);

***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
                image: NetworkImage(widget.image,),
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    ***REMOVED***
***REMOVED***
                    "Gigantic Glute Workout",
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    ***REMOVED***,),
***REMOVED***
***REMOVED***,
***REMOVED***
              FadeAnimationDown(1.4,Text("with Michael Reeves",
***REMOVED***
***REMOVED***
***REMOVED***
    ***REMOVED***),),

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
        ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
        ***REMOVED***,
***REMOVED***
                        "4.0",
    ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
        ***REMOVED***,
***REMOVED***
***REMOVED***
        ***REMOVED***,
***REMOVED***
                        "(2460)",
    ***REMOVED***
***REMOVED***
***REMOVED***
    ***REMOVED***
        ***REMOVED***,
    ***REMOVED***
    ***REMOVED***,),
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  ***REMOVED***
***REMOVED***
        ***REMOVED***,
      ***REMOVED***,
***REMOVED***
***REMOVED***
                    ***REMOVED***,
    ***REMOVED***),
***REMOVED***
***REMOVED***,
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***,),
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***,),
***REMOVED***
***REMOVED***
                "Reeves is back at it again with his classic glutes workout, ready to take you into a new level of satisfaction and fitness. He's ready to twist it, bop it, pull it, anything you think is necessary to get you a rocking hot body. This workout focuses on the glutes, and strecthing them into the curves you have so desperately desired.",
***REMOVED***color: Colors.grey, height: 1.5,
***REMOVED***
***REMOVED***,),
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***,),
***REMOVED***
***REMOVED***
***REMOVED***,
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***"Cost: \$25", style: TextStyle(
  ***REMOVED***
***REMOVED***
***REMOVED***
      ***REMOVED***,)
    ***REMOVED***,),
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED******REMOVED***,
***REMOVED***
***REMOVED***
***REMOVED***
        ***REMOVED***,),
***REMOVED***
  ***REMOVED***borderRadius: BorderRadius.circular(20)),
    ***REMOVED***,),),
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  ***REMOVED***
***REMOVED***
